swagger: "2.0"
info:
  description: AUA backend API
  version: "1.0.0"
  title: "AUA API"
basePath: "/api/v1"
schemes:
  - http
  - https
definitions:
  PingResponse:
    type: "object"
paths:
  /contact:
    post:
      operationId: saveContact
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /file/download/job/{jobId}/file/{fileId}:
    get:
      operationId: downloadFile
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: jobId
          in: path
          type: string
          format: uuid
          required: true
        - name: fileId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /file/search:
    post:
      operationId: searchFileList
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /file/{id}:
    get:
      operationId: getFile
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /file:
    post:
      operationId: uploadFile
      responses:
        200:
          description: OK
  /auth/login:
    post:
      operationId: login
      # security:
      # - authAnyRole: []
      #   - business: []
      #   - individual: []
      #   - admin: []
      responses:
        200:
          description: OK
  /auth/logout:
    post:
      operationId: logout
      # security:
      #   - authAnyRole: []
      # security:
      #   - business: []
      #   - individual: []
      #   - admin: []
      responses:
        200:
          description: OK
  /auth/forgot_password:
    post:
      operationId: forgotPassword
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/impersonate:
    post:
      operationId: impersonate
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/invite:
    post:
      operationId: inviteUser
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/reset_password:
    post:
      operationId: resetPassword
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/reset_password/{token}:
    get:
      operationId: retrievePassword
      # security:
      #   - authAnyRole: []
      parameters:
        - name: token
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /auth/signin:
    post:
      operationId: signin
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/user:
    get:
      operationId: getAuthUser
      responses:
        200:
          description: OK
  /auth/sso/google:
    post:
      operationId: ssoGoogle
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /user:
    get:
      operationId: listAllUsers
      # security:
      #   - authAdminOrAgent: []
      responses:
        200:
          description: OK
  /user/:id:
    delete:
      operationId: deleteUser
      # security:
      #   - authAdminOrAgent: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/set_password:
    post:
      operationId: setUserPassword
      # security:
      #   - authAdminOrAgent: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/agent:
    get:
      operationId: listAgents
      # security:
      #   - authAdminOrAgent: []
      responses:
        200:
          description: OK
  /user/change_password:
    post:
      operationId: changePassword
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /job_template:
    post:
      operationId: saveJobTemplate
      # security:
      #   - authAdmin: []
      responses:
        200:
          description: OK
    get:
      operationId: listJobTemplates
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /job_template/{id}:
    get:
      operationId: getJobTemplate
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteJobTemplate
      # security:
      #   - authAdmin: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /doc_template:
    post:
      operationId: saveDocTemplate
      # security:
      #   - authAdmin: []
      responses:
        200:
          description: OK
    get:
      operationId: listDocTemplates
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /doc_template/{id}:
    get:
      operationId: getDocTemplate
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /doc_template/{id}/apply:
    post:
      operationId: applyDocTemplate
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /doc_template/{id}/pdf:
    post:
      operationId: createPdfFromDocTemplate
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteDocTemplate
      # security:
      #   - authAdmin: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /portfolio:
    post:
      operationId: savePortfolio
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
    get:
      operationId: listPortfolio
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
  /portfolio/{id}:
    get:
      operationId: getPortfolio
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deletePortfolio
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /job:
    post:
      operationId: saveJob
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
    get:
      operationId: listJob
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /job/search:
    post:
      operationId: searchJob
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /job/generate:
    post:
      operationId: generateJob
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
  /job/{id}:
    get:
      operationId: getJob
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteJob
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /job/{id}/sign:
    post:
      operationId: signJobDoc
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /job/{id}/assign:
    post:
      operationId: assignJob
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /job/{id}/notify:
    get:
      operationId: listJobNotifies
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: notifyJob
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /job/{id}/notify/read:
    post:
      operationId: markJobNotifyRead
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /recurring:
    get:
      operationId: listRecurring
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
    post:
      operationId: saveRecurring
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
  /recurring/healthcheck:
    get:
      operationId: healthCheckRecurring
      responses:
        200:
          description: OK
  /recurring/:id:
    get:
      operationId: getRecurring
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteRecurring
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /recurring/:id/run:
    post:
      operationId: runRecurring
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /message:
    post:
      operationId: listMessage
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
  /message/count/unread:
    get:
      operationId: getMessageUnreadCount
      responses:
        200:
          description: OK
  /message/:id:
    get:
      operationId: getMessage
      # security:
      #   - authClient: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stats:
    get:
      operationId: getAdminStats
      responses:
        200:
          description: OK
